### ISSUE TITLE
Can't run AliceVision photogrametry 

### ISSUE THREAD

**Issue by artofka** [sideeffects/GameDevelopmentToolset#128]
"01_Camera_init" node inside "sop_av_initialize1" catch error:

Error | Python error: Traceback (most recent call last):File "", line 40, in File "opdef:/gamedev::Sop/sop_av_initialize::2.0?PythonModule", line 42, in logFile "/opt/hfs17.5.173/python/lib/python2.7/subprocess.py", line 394, in __init__errread, errwrite)File "/opt/hfs17.5.173/python/lib/python2.7/subprocess.py", line 1047, in _execute_childraise child_exceptionOSError: [Errno 2] No such file or directory
-- | --

Opensuse 42.2 / Houdini 17.5.173 / AliceVision-2.1.0

**Comment by Ambrosiussen** [comment]
Hi,

For future reference please send issues to support@sidefx.com. We check those daily.

As for your issue, did you save the .hip before cooking?

Paul

**Comment by artofka** [comment]
Yes, save the scene before cookong. When open it, I get this error:
![image](https://user-images.githubusercontent.com/28753260/59146611-1729fb00-89f9-11e9-84cb-95883f1c5c91.png)
