### ISSUE TITLE
Gaea bridge import error

### ISSUE THREAD

**Issue by bazarus** [sideeffects/GameDevelopmentToolset#156]
Scene from last build of Gaea and build 190 of GDT doesn't loads. Error from Reset Parameters:

```
Error running callback:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "opdef:/gamedev::Sop/sop_gea_tor_processor?PythonModule", line 112, in ResetInterface
  File "opdef:/gamedev::Sop/sop_gea_tor_processor?PythonModule", line 173, in LoadXML
  File "C:/soft/houdini/17.5.229/houdini/python2.7libs\hou.py", line 37505, in __init__
    this = _hou.new_IntParmTemplate(*args, **kwargs)
OperationFailed: The attempted operation failed.
Invalid name
```

**Comment by Ambrosiussen** [comment]
Hi, could you send me an example .tor file where this happens?

Paul
