### ISSUE TITLE
Auto update seems to get issues

### ISSUE THREAD

**Issue by Geo2D3D** [sideeffects/GameDevelopmentToolset#183]
Hi, 

In Houdini 18.0.310 ran as an admin in an up to date W10, when I use the embedded updater, I get the following console alert:

Traceback (most recent call last):
  File "update_toolset", line 121, in on_updatebtn_press
  File "update_toolset", line 283, in on_dialog_close
  File "update_toolset", line 236, in unzip_file
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.310\python27\lib\zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.310\python27\lib\zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.310\python27\lib\zipfile.py", line 1083, in _extract_member
    file(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: 'C:\\Users\\Georges\\Documents\\houdini18.0\\SideFXLabs\\310 (local)\\bin\\CapturingReality.CoordinateSystems.dll'

**Comment by lkruel** [comment]
Looks like you're trying to install over your existing install which is currently in use

**Comment by Geo2D3D** [comment]
Hi!
I'm a developer too :)
You're making a really sophisticated job, thank you. However, UX could be better. 
1) An alert could be showing up in Houdini itself if we don't get the latest version installed.
2)  At least, if the installed version and the "new" one are identical, you could either obfuscate the console alert, or make it display a note saying that we already get the latest version installed... 
This way, you would spare time, by not having to answer notes like this one :)

**Comment by lkruel** [comment]
absolutely! I've added a bug in our database to catch this earlier and hopefully this will be addressed sooner than later.

**Comment by Geo2D3D** [comment]
Cool! Thank you very much!
