### ISSUE TITLE
Houdini 18+

### ISSUE THREAD

**Issue by idorurez** [sideeffects/GameDevelopmentToolset#185]
Getting this every time I open with 18:

```
[2020-01-06 16:27:50,641] ERROR in search: Error parsing '/nodes/sop/gamedev--sop_flowmap_obstacle-3.0'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.287\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.287/houdini/python2.7libs\houdinihelp\api.py", line 549, in run
    indexer.update_with(w, pages)
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.287/houdini/python2.7libs\bookish\search.py", line 465, in update_with
    writer, pages, update_paths, needs_delete=changed
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.287/houdini/python2.7libs\bookish\search.py", line 494, in index_paths_with
    for doc in self.documents(pages, path):
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.287/houdini/python2.7libs\bookish\search.py", line 401, in documents
    jsondata = pages.json(path, postprocess=False)
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.287/houdini/python2.7libs\bookish\wiki\wikipages.py", line 611, in json
    self._pre_pipeline.apply(jsondata, wcontext)
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.287/houdini/python2.7libs\bookish\wiki\pipeline.py", line 116, in apply
    v.apply(block, context)
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.287/houdini/python2.7libs\houdinihelp\hpages.py", line 324, in apply
    self.apply(subblock, context)
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.287/houdini/python2.7libs\houdinihelp\hpages.py", line 311, in apply
    block["value"] = self._parse_opdef(path, block["value"])
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.287/houdini/python2.7libs\houdinihelp\hpages.py", line 296, in _parse_opdef
    nodetype, version)
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.287/houdini/python2.7libs\houdinihelp\api.py", line 835, in components_to_path
    parts = ["/nodes/", table_to_dir[table], "/"]
KeyError: u'gamedev::Sop'

```

**Comment by ziranjuanchow** [comment]
I got the same error in houini18.
