### ISSUE TITLE
Games Baker (Beta) gives errors

### ISSUE THREAD

**Issue by joschy3D** [sideeffects/GameDevelopmentToolset#187]
Hi,
I'm using Houdini 18.0.391 Indie with the labs dev tools 391.
Error when I try to bake: 
Error | Error rendering child: /out/games_baker1/shell5

Error in the shell5 node:
Error | Python error: Traceback (most recent call last):File "<stdin>", line 1, in <module>File "opdef:/labs::Driver/games_baker::2.0?PythonModule", line 20, in set_current_meshAttributeError: 'NoneType' object has no attribute 'path'
-- | --

I have only a Target Mesh (Low) loaded to bake the cd attribute to a texture
[FlowMap.zip](https://github.com/sideeffects/GameDevelopmentToolset/files/4397816/FlowMap.zip)

**Comment by Polyrhythm** [comment]
+1, same problem, same Houdini version except mine is commercial

**Comment by Polyrhythm** [comment]
The code that errors is here:
https://github.com/sideeffects/SideFXLabs/blob/65b392c17f51afbc658ce84a0f12add39f253dd9/otls/games_baker.hda/labs_8_8Driver_1games__baker_8_82.0/PythonModule#L20

It seems to expect both a source and target mesh. If you set the source and target mesh to be the same in your example, @joschy3D, you can get the baking to work as you want, I think.

**Comment by joschy3D** [comment]
yep, that's solve it :) Thank you
