### ISSUE TITLE
LOD tool fails in 17.0.352 with GameDevTools 1.62

### ISSUE THREAD

**Issue by drichardson** [sideeffects/GameDevelopmentToolset#87]
The gamedev LOD hierarchy tool fails with the following python error every time I try to use it:

```
Error running callback:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "opdef:/gamedev::Object/obj_lod_hierarchy?PythonModule", line 32, in MainFunction
AttributeError: 'NoneType' object has no attribute 'destroy'
```

Houdini Indie 17.0.352 
GameDevTools 1.60

Same thing also happens with GameDevTools 1.62.

### Steps to Reproduce
1. Unzip attached file.
2. Select /obj/obj_lod_hierarchy1
3. Press the Export button in the parameter window.

### Result
The error above appears on the console.

[lod_test.zip](https://github.com/sideeffects/GameDevelopmentToolset/files/2490441/lod_test.zip)

**Comment by drichardson** [comment]
Seems to be fixed in 1.64.
